import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {deflateSync} from 'node:zlib';
import {inspectImageSequence} from '../src/protocol/image_sequence.ts';
const sha=(b:Buffer|string)=>createHash('sha256').update(b).digest('hex');
function chunk(type:string,b:Buffer){const body=Buffer.concat([Buffer.from(type),b]);let crc=0xffffffff;for(const x of body){crc^=x;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}const size=Buffer.alloc(4),sum=Buffer.alloc(4);size.writeUInt32BE(b.length);sum.writeUInt32BE((crc^0xffffffff)>>>0);return Buffer.concat([size,body,sum]);}
async function fixture(){const root=await mkdtemp(join(tmpdir(),'art-segments-')),parts:any[]=[],records:any[]=[],frames:any[]=[];for(let i=0;i<2;i++){const folder=`segment_${String(i).padStart(5,'0')}`;await mkdir(join(root,folder));const pixel=Buffer.from([10+i*80,20,30,128]),h=Buffer.alloc(13);h.writeUInt32BE(1,0);h.writeUInt32BE(1,4);h[8]=8;h[9]=6;const png=Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',h),chunk('IDAT',deflateSync(Buffer.concat([Buffer.from([0]),pixel]))),chunk('IEND',Buffer.alloc(0))]);await writeFile(join(root,folder,'frame_00000.png'),png);const frame={index:0,location:'frame_00000.png',sha256:sha(png),bytes:png.length,alphaExtrema:[128,128],rgbaSha256:sha(pixel)};frames.push(frame);const child={schema:'craft-image-sequence/v1',encoding:'png',width:1,height:1,bitDepth:8,channels:'rgba',alphaRepresentation:'straight-png',colorSpace:'unknown',frameRate:{num:2,den:1},frameCount:1,durationTicks:'1',timeBase:{num:1,den:2},frames:[frame]},text=JSON.stringify(child);await writeFile(join(root,folder,'sequence.json'),text);const part={firstFrame:i,frameCount:1,start:i?{num:1,den:2}:{num:0,den:1},end:i?{num:1,den:1}:{num:1,den:2}};parts.push(part);records.push({...part,location:folder+'/sequence.json',sha256:sha(text)});}const descriptor:any={schema:'craft-segmented-render-checkpoint/v1',state:'verified',binding:{projectSha256:'a'.repeat(64),runtimeSha256:'b'.repeat(64),composition:{name:'Intro',width:1,height:1,frameRate:2,duration:1},chunkBytes:4,parts},frameCount:2,frameRate:{num:2,den:1},segments:records};const save=async()=>{const text=JSON.stringify(descriptor);await writeFile(join(root,'segments.json'),text);return sha(text);};return {root,descriptor,frames,save};}
test('segmented producer returns continuous pixels and child manifest evidence',async()=>{const f=await fixture();try{const d=await inspectImageSequence(f.root,'segments.json',await f.save());assert.equal(d.frameCount,2);assert.deepEqual(d.frames.map((x:any)=>x.index),[0,1]);assert.equal(d.frames[1].location,'segment_00001/frame_00000.png');assert.equal(d.segmentManifestRefs.length,2);}finally{await rm(f.root,{recursive:true});}});
test('segment gaps, overlap, rational time and budget fail',async()=>{for(const fault of ['gap','overlap','time','budget']){const f=await fixture();try{if(fault==='gap')f.descriptor.segments[1].firstFrame=2;if(fault==='overlap')f.descriptor.segments[1].firstFrame=0;if(fault==='time')f.descriptor.segments[1].start={num:1,den:3};if(fault==='budget')f.descriptor.binding.chunkBytes=3;await assert.rejects(inspectImageSequence(f.root,'segments.json',await f.save()),/image_sequence_/);}finally{await rm(f.root,{recursive:true});}}});
test('actual segment tampering and partial producer fail',async()=>{for(const fault of ['pixels','state']){const f=await fixture();try{if(fault==='pixels')await writeFile(join(f.root,'segment_00001/frame_00000.png'),'bad');else f.descriptor.state='partial';await assert.rejects(inspectImageSequence(f.root,'segments.json',await f.save()),/image_sequence_/);}finally{await rm(f.root,{recursive:true});}}});
test('Film collected sequence retains original ranges without relaxing old v1',async()=>{const f=await fixture();try{const source=await f.save();await mkdir(join(f.root,'film'));for(let i=0;i<2;i++){const {copyFile}=await import('node:fs/promises');await copyFile(join(f.root,`segment_${String(i).padStart(5,'0')}/frame_00000.png`),join(f.root,'film',`frame_${String(i).padStart(5,'0')}.png`));}const d:any={schema:'filmcraft-collected-sequence/v1',encoding:'png',width:1,height:1,bitDepth:8,channels:'rgba',alphaRepresentation:'straight-png',colorSpace:'unknown',frameRate:{num:2,den:1},frameCount:2,durationTicks:'2',timeBase:{num:1,den:2},sourceSequenceSha256:source,segments:f.descriptor.segments.map((x:any)=>({firstFrame:x.firstFrame,frameCount:x.frameCount,sourceSha256:x.sha256})),frames:f.frames.map((x:any,i:number)=>({...x,index:i,location:`frame_${String(i).padStart(5,'0')}.png`}))};let text=JSON.stringify(d);await writeFile(join(f.root,'film/sequence.json'),text);await inspectImageSequence(f.root,'film/sequence.json',sha(text));d.segments[1].firstFrame=0;text=JSON.stringify(d);await writeFile(join(f.root,'film/sequence.json'),text);await assert.rejects(inspectImageSequence(f.root,'film/sequence.json',sha(text)),/image_sequence_/);}finally{await rm(f.root,{recursive:true});}});
